- README.md
- app.js
- config/config.sample.yaml
- config/slack-config-schema.yaml
FYI: I have never written Node before, it feels like I should probably pull this out into at least two files, and I have no idea how to write tests for this thing, but I'd like to.
This is Kegan's HOWTO example, made configurable
It is woefully insufficient for real use, and in particular requires you
to both hard-code your list of channels in advance, and somehow know the
slack internal channel ID of the channels you are bridging.
> Initial commit

- app.js
- lib/hook-handler.js
- tests/hook-handler.spec.js
> Pull out hook handler

- lib/hook-handler.js
- lib/matrix-handler.js
- lib/substitutions.js
- tests/hook-handler.spec.js
- tests/matrix-handler.spec.js
Covers &<>
Still maybe to do:
* Emoji
* Emotes
* Font stylings
* Anything else which comes up
> Perform special character substitution

- app.js
- lib/matrix-handler.js
- lib/slack-hook-handler.js
- package.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/matrix-org/matrix-appservice-slack/5)
> Fix lint errors

- app.js
- lib/matrix-handler.js
- lib/substitutions.js
- tests/matrix-handler.spec.js
But not yet slack -> matrix
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/matrix-org/matrix-appservice-slack/6)
> Support images matrix -> slack

- app.js
- config/config.sample.yaml
- config/slack-config-schema.yaml
- lib/rooms.js
- lib/slack-hook-handler.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/matrix-org/matrix-appservice-slack/7)
> Require auth tokens on slack webhook requests

- lib/MatrixUser.js
> Use MXID if the user has not display name

- lib/Main.js
This is basically a mirror of https://github.com/matrix-org/matrix-appservice-gitter/pull/66
> Warn on invites to DMs

- config/slack-config-schema.yaml
- lib/Main.js
Some homeservers only allow their AS to connect to them over a private network, but we want a public url for media.
> Add option for media_url

- package.json
We're pinning this because the author doesn't seem all that responsive :/
> Pin slackdown to recieve support for triple `

- app.js
- config/config.sample.yaml
- config/slack-config-schema.yaml
- lib/AdminCommands.js
- lib/BridgedRoom.js
- lib/Main.js
- lib/OAuth2.js
- lib/Provisioning.js
- lib/SlackGhost.js
- lib/SlackHookHandler.js
- lib/substitutions.js
- package.json
This uses the new logging component for matrix-appservice-bridge.
> Add (winston) logging support

- config/slack-config-schema.yaml
- lib/Main.js
> add a dbdir config to customise location of the stores

- lib/Main.js
- lib/substitutions.js
> Convert Riot Pills to Slack mentions

- lib/Main.js
- lib/OAuth2.js
- lib/SlackHookHandler.js
- package.json
These are new endpoints to facilitate a rich UX experience when bridging using the bot API. You can use this to list channels and teams your matrix_id is associated with. This also includes some important endpoints for fetching and storing the bot token for a team.
> Bot api provisioning bits

- lib/BridgedRoom.js
- lib/SlackEventHandler.js
- lib/SlackGhost.js
- lib/substitutions.js
> Enable support for edits by copying it out of Gitter

- lib/BridgedRoom.js
> Add support for conversion of snippets to code messages in matrix

- lib/substitutions.js
> Better to leave the text un-modified if we dont understand the emoji

- .eslintrc
- lib/substitutions.js
Signed off by: Stuart Mumford <stuart@cadair.com>
> Fix snowflake

- lib/BaseSlackHandler.js
- lib/BridgedRoom.js
- lib/Main.js
- lib/SlackEventHandler.js
- lib/SlackGhost.js
- package.json
fixes #70 and fixes #100 (although not all the other things that this enables)
> Implement message deletion

- lib/SlackGhost.js
> Update SlackGhost to support display name and avatar lookups for bots

- app.js
- config/config.sample.yaml
- config/slack-config-schema.yaml
- lib/Main.js
- lib/substitutions.js
We really need to update our docs in general but hopefully mentioning these two options in the example config is at least a step in the right direction.
@kingoftheconnors @spantaleev
Signed off By: Stuart Mumford (stuart@cadair.com)
> Remove duplication of registration path and tidy example config

- lib/BridgedRoom.js
- lib/SlackEventHandler.js
> Fix username and channel substitutions in edits

- lib/BridgedRoom.js
- lib/Main.js
- lib/SlackGhost.js
Initial work on threads to replies.
So far only matrix replies get sent to slack threads, and I need to add stripping the reply fallbacks.
builds on ~#129~ and ~#130~
Sorta fixes #45 and far as I can tell fixes #57 
Signed off By: Stuart Mumford (stuart@cadair.com)
> Threads replies bridging

- lib/SlackEventHandler.js
- lib/SlackGhost.js
@umitalp This is #126 rebased onto develop. There have been a bunch of changes on develop since I opened the original version of this (against master like a fool).
The behaviour of this with the changes to bot usernames is... surprising:
@umitalp I hope you don't mind me rebasing this, please let me know if you look this over and notice anything I have messed up in the process.
> Attachments 3: This time they are Rebased

- lib/Main.js
- lib/substitutions.js
Signed Off By: Stuart Mumford (stuart@cadair.com)
fixes #148
> Fix mentions

- lib/BaseSlackHandler.js
- lib/BridgedRoom.js
- lib/SlackEventHandler.js
- lib/SlackGhost.js
- lib/SlackHookHandler.js
- lib/substitutions.js
- package.json
fixes #150 and also fixes #151 
Sorry this ended up being way more of an undertaking than I hoped.
Signed off by: Stuart Mumford (stuart@cadair.com)
> Bug fixes for develop!

- lib/substitutions.js
> Verify that the ID exists before storing it in the displaymap

- lib/SlackHookHandler.js
I got angry and made this async syntax. I think we forgot to resolve a promise in the old code. Fixes #158
> Hotfix webhook bug

- lib/BridgedRoom.js
- lib/SlackGhost.js
This turned out to be much harder because of edits, but it works now.
> Correctly add reply fallbacks on messages in threads, and edits in threads

- package.json
- src/SlackHookHandler.ts
- src/tests/integration/SlackToMatrixTest.ts
- src/tests/unit/BridgedRoomTest.ts
- src/tests/unit/MatrixUserTest.ts
- src/tests/unit/substitutionsTest.ts
- src/tests/utils/fakeMain.ts
~Depends on #153~
This adds the skeleton work needed to support integration tests, as well as adding a simple test as an example.
> Integration testing

- Dockerfile
> Copy the config folder into the working dir

- src/BridgedRoom.ts
- src/SlackEventHandler.ts
- src/SlackGhost.ts
- src/substitutions.ts
> Correctly bookeep threads when we reply on matrix

- README.md
- docs/datastores.md
- src/Main.ts
- src/datastore/NedbDatastore.ts
- src/scripts/migrateToPostgres.ts
- tslint.json
This PR adds a script to migrate data from NeDB to PostgreSQL.
> Datastore migration script

- src/Main.ts
- src/SlackHookHandler.ts
- src/SlackRTMHandler.ts
Continuing to see duplicate messages from using events + rtm, so refactoring the checking code a smidge
> remove main.rtmTeams and check via SlackRTM

- changelog.d/243.bugfix
- src/Main.ts
> Throw an error if the bot token doesn't start with xoxb-

- config/slack-config-schema.yaml
> Fix schema log level

- changelog.d/246.misc
- src/Main.ts
- src/SlackClientFactory.ts
- src/SlackEventHandler.ts
- src/SlackRoomStore.ts
Deploying this to matrix.org failed, but we lack a lot of logging to understand what went wrong. This should hopefully improve things.
> Add more logging to startup routine

- changelog.d/254.bugfix
- src/OAuth2.ts
- src/Provisioning.ts
- src/tests/unit/ProvisioningTest.ts
- src/tests/utils/fakeExpress.ts
- src/tests/utils/fakeMain.ts
> Don't require puppeting parameter on getauth

- changelog.d/262.bugfix
- src/BaseSlackHandler.ts
- src/SlackEventHandler.ts
- src/tests/integration/SlackToMatrixTest.ts
- src/tests/utils/fakeMain.ts
Unless we are dealing with message_deleted
> Ignore tombstone events

- changelog.d/268.doc
- docs/datastores.md
> Add docker example to datastores

- README.md
- config/config.sample.yaml
Made the uses of all variables in the config file explicit, and added small sections for proxying and docker (although I haven't tested the docker command myself. @Cadair, you deploy the bridge from docker yourself, right? Could you take a look?).
Please scan over it and correct anything that shows my sore lack of experience.
> Updated documentation

- changelog.d/274.bugfix
- config/config.sample.yaml
- package.json
- src/SlackGhost.ts
- src/datastore/postgres/PgDatastore.ts
Hopefully fixes https://github.com/matrix-org/matrix-appservice-slack/issues/144
This change makes it so that users cannot attempt multiple updates against a ghost's profile.
> Ensure only one update can be performed against a ghost

- docs/getting_started.md
Signed-off-by: Tim Stahel <swedneck@swedneck.xyz>
> fix "syanpse" and "configruation" misspellings

- changelog.d/291.bugfix
- src/SlackGhost.ts
- src/SlackHookHandler.ts
> Fix mattermost dedupe and missing displaynames

- changelog.d/288.bugfix
- src/SlackClientFactory.ts
- src/SlackRTMHandler.ts
> Adjust Logger interface to new slack typescript api

- changelog.d/295.feature
- config/config.sample.yaml
- config/slack-config-schema.yaml
- src/IConfig.ts
- src/Main.ts
> Add appservice port option in the config.

- changelog.d/280.bugfix
- package-lock.json
- package.json
- src/BridgedRoom.ts
- src/Main.ts
- src/datastore/Models.ts
- src/datastore/NedbDatastore.ts
- src/datastore/postgres/PgDatastore.ts
- src/substitutions.ts
- src/tests/unit/substitutionsTest.ts
- src/tests/utils/fakeDatastore.ts
- src/tests/utils/fakeIntent.ts
- src/tests/utils/fakeMain.ts
> Refactor Matrix -> Slack subsitutions

- changelog.d/299.bugfix
- src/substitutions.ts
- src/tests/unit/substitutionsTest.ts
> Fix Markdown link substitution

- CONTRIBUTING.md
Because we don't actually mention this anywhere
> Add note about newsfiles

- changelog.d/324.bugfix
- src/Main.ts
> Fix edits from matrix appearing as fallback text

- changelog.d/325.bugfix
- src/BridgedRoom.ts
> Queue M->S messages in a per-room queue

- changelog.d/325.bugfix
- src/BridgedRoom.ts
- src/Main.ts
- src/SlackRoomStore.ts
- src/datastore/Models.ts
- src/datastore/NedbDatastore.ts
- src/datastore/postgres/PgDatastore.ts
- src/datastore/postgres/schema/v4.ts
- src/rooms/UserAdminRoom.ts
- src/tests/utils/fakeDatastore.ts
> Support user admin rooms

- changelog.d/329.bugfix
- src/Main.ts
Fix an issue where commands would loop, tests for this can be found in #330 because we had to adjust our test rig to support it.
> Do not handle commands from the bot user

- changelog.d/340.feature
- src/Main.ts
- src/SlackGhostStore.ts
- src/SlackRTMHandler.ts
- src/TeamSyncer.ts
- src/tests/unit/SlackGhostStore.ts
- src/tests/utils/fakeDatastore.ts
This will create a private room if a user talks on the slack side but the room doesn't exist yet.
> Support creating private chats on demand

- changelog.d/358.misc
- config/config.sample.yaml
- package.json
- src/IConfig.ts
- src/Main.ts
- src/Provisioning.ts
- src/tests/unit/ProvisioningTest.ts
- tsconfig.json
This is mostly for just making the code less messy, thoughts and opinions on decorators appreciated.
> Use decorators for provisioning commands

- changelog.d/366.doc
- docs/getting_started.md
EX -> Example
The full word seems more accessible. I had not heard EX before.
ports -> port
As far as I can tell only one port is needed.
> Minor wording suggestions in the docs

- changelog.d/392.bugfix
- src/SlackHookHandler.ts
> Do not send error if HTTP connection is closed

- changelog.d/402.feature
- src/BridgedRoom.ts
- src/Main.ts
This change makes it so that the bridge follows m.room.tombstone events
> Support room upgrades

- changelog.d/408.bugfix
- src/SlackGhost.ts
> Ensure user's profile is not modified when they delete a bot

- changelog.d/411.misc
- config/config.sample.yaml
- config/slack-config-schema.yaml
- src/IConfig.ts
- src/Main.ts
- src/rooms/UserAdminRoom.ts
This never made it into the configuration before.
Also fix a typo with the provisioning flag while we are here.
> Add ability to disable puppeting

- changelog.d/418.bugfix
- src/rooms/UserAdminRoom.ts
> Fix logic error

- changelog.d/426.bugfix
- src/datastore/postgres/PgDatastore.ts
Fixing a bug introduced by #419
> Upsert new tokens to linked_accounts

- changelog.d/423.feature
- config/config.sample.yaml
- config/slack-config-schema.yaml
- src/IConfig.ts
- src/Main.ts
To make the bot look a bit prettier, and to avoid that issue where joining over federation breaks. https://github.com/matrix-org/synapse/issues/2807
> Set profile on startup

- changelog.d/438.misc
- docs/getting_started.md
- src/substitutions.ts
Changes mentions of Riot, except for one in the Changelog.
> Rebrand: Riot -> Element

- changelog.d/450.bugfix
- src/BridgedRoom.ts
- src/SlackResponses.ts
> Fetch slack file info if we are missing a mimetype

- changelog.d/459.bugfix
- package-lock.json
- package.json
in 1.13.1 we were returning undefined for `sendEvent` which was causing issues inserting events into the DB, in turn causing #452
> Bump matrix-appservice-bridge@1.13.2

- changelog.d/463.bugfix
- changelog.d/466.bugfix
- package.json
- src/BridgedRoom.ts
- src/SlackGhost.ts
> Use axios and more safety around file uploads

- changelog.d/474.bugfix
- config/config.sample.yaml
- config/slack-config-schema.yaml
> schema-fixes for direct_messages

- changelog.d/509.bugfix
- src/BridgedRoom.ts
Fixes: #488 
Related: https://github.com/vector-im/element-web/issues/13926
> Append /ufe0f to thumbsup and thumsdown reactions

- changelog.d/499.bugfix
- package-lock.json
- package.json
- src/BridgedRoom.ts
- src/datastore/postgres/PgDatastore.ts
This boils down to awaiting a promise.
> Fix issue where threading would break

- changelog.d/515.feature
- src/BridgedRoom.ts
> Join slack client to channel if they aren't in it.

- changelog.d/527.bugfix
- src/Main.ts
Fix https://github.com/matrix-org/matrix-appservice-slack/issues/526
It was removed in 912f63733f37634ed171f6b315dd291bf30fc660.
> Do not respond to own messages

- changelog.d/538.misc
- config/config.sample.yaml
- config/slack-config-schema.yaml
> Define the encryption config

- changelog.d/556.misc
- src/app.ts
> Fix event emitter log spam

- changelog.d/559.feature
- src/Main.ts
- src/SlackRTMHandler.ts
- src/rooms/UserAdminRoom.ts
> Add logout command

- changelog.d/558.bugfix
- src/SlackRTMHandler.ts
> Fix DMs not persisting

- changelog.d/563.feature
- src/Main.ts
- src/SlackRTMHandler.ts
- src/TeamSyncer.ts
This PR ensures that private channels are correctly synchronised on startup with the correct membership and visibility
> Ensure private channels are syncronised on startup

- changelog.d/564.misc
- package-lock.json
- package.json
- src/datastore/postgres/PgDatastore.ts
- src/datastore/postgres/schema/v12.ts
Depends on https://github.com/matrix-org/matrix-appservice-bridge/pull/285
> Add supporting code for latest enc bridge efforts

- changelog.d/576.bugfix
- src/TeamSyncer.ts
We should never have encrypted public rooms
> Only encrypt private rooms

- config/config.sample-complete.yaml
- config/config.sample.yaml
- package.json
- tests/unit/ConfigTest.ts
Depends on #582 
To try and avoid having issues where we ship a release with a broken sample config
> Validate sample and full config

- changelog.d/613.feature
- src/Main.ts
- src/SlackRTMHandler.ts
This uses the bot intent to do a simple state check.
> Automatically invite users to private rooms when a new message comes in over their RTM stream

- changelog.d/620.bugfix
- src/rooms/UserAdminRoom.ts
This got missed from the list ages ago.
> Add help text for whoami command

- changelog.d/621.feature
- src/Main.ts
- src/OAuth2.ts
- templates/oauth_result.html.njk
(Also fix a small bug around the blocked metric name)
> Add metric for tracking our success rate with oauth

- changelog.d/666.feature
- src/Main.ts
- tests/utils/harness.ts
This is something we've had in Bifrost and the IRC bridge for a while, but missed out on it on this bridge. This code basically pings the homeserver through a room to ask if it's alive, and if not if warns in the logs.
> Ping homeserver on startup to check connectivity

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
- changelog.d/686.doc
Based on https://github.com/matrix-org/matrix-appservice-bridge/blob/develop/CONTRIBUTING.md
> Add new contrib guide

- .github/CODEOWNERS
- .github/workflows/sign-off.yml
- changelog.d/58.misc
- changelog.d/693.misc
> Add sign-off and CODEOWNERS

- README.md
> Drop buildkite badge

- changelog.d/696.bugfix
- src/OAuth2.ts
- tests/unit/ProvisioningTest.ts
> Add reactions:write to user scopes

- changelog.d/704.bugfix
- package.json
- src/Main.ts
- src/Provisioning.ts
- yarn.lock
Fixes #702 by upgrading a dependency.
https://github.com/matrix-org/matrix-appservice-bridge/releases/tag/5.1.0
> Update matrix-appservice-bridge to 5.1.0

- changelog.d/710.misc
- package.json
- src/AdminCommands.ts
- src/BaseSlackHandler.ts
- src/BridgedRoom.ts
- src/Main.ts
- src/MatrixUser.ts
- src/OAuth2.ts
- src/Provisioning.ts
- src/SlackClientFactory.ts
- src/SlackEventHandler.ts
- src/SlackGhost.ts
- src/SlackGhostStore.ts
- src/SlackHookHandler.ts
- src/SlackRTMHandler.ts
- src/SlackRoomStore.ts
- src/TeamSyncer.ts
- src/app.ts
- src/datastore/postgres/PgDatastore.ts
- src/rooms/UserAdminRoom.ts
- src/scripts/migrateToPostgres.ts
- src/substitutions.ts
- tests/integration/PgDatastoreTest.ts
- yarn.lock
> Update matrix-appservice-bridge to 6.0.0

- changelog.d/712.misc
- src/SlackEventHandler.ts
The logs were full of this pointless line.
> Remove noisy log line

- changelog.d/714.bugfix
- src/rooms/UserAdminRoom.ts
> Fix possible null lookup in `whoami` command

- changelog.d/721.bugfix
- src/BridgedRoom.ts
- src/Main.ts
- src/RoomCreation.ts
- src/SlackGhost.ts
- src/SlackRTMHandler.ts
- src/TeamSyncer.ts
Also:
- fix DM metadata on startup
- improve cleanup of DM when Matrix user leaves it
- improve migration of DM when duplicate DM is created
> Improve calculation of DM names & avatars
