app.js
config/config.sample.yaml
config/slack-config-schema.yaml
lib/rooms.js
lib/slack-hook-handler.js
tests/slack-hook-handler.spec.js

Only supported if a slack_master_token is specified, which is a token
with permission to view history of each room being bridged.

Support sending images slack -> matrix

---

README.md

I succeeded on using the Slack bridge to bridge Mattermost channels and Matrix rooms, so I'm adding a mention about it to the README.

Add Mattermost compatibility to README

---

lib/SlackGhost.js
package.json

Fix #44. Actually Slack does not use markdown, but its own format.

Translate slack messages to HTML

---

lib/substitutions.js

While you might not always want `@channel` in slack to notify you having it come through as `@room` is the matrix way, and it's what power levels are for :laughing:

Change @channel to @room

---

package.json

The pin was so we could get the prometheus client on the bridge, but that has since been merged. This also contains a bug fix for ``_isRemoteUser`` which means our DM invite rejections will work.

Don't pin on matrix-appservice-bridge anymore

---

lib/BaseSlackHandler.js
lib/BridgedRoom.js
lib/SlackEventHandler.js
lib/SlackGhost.js
lib/SlackHookHandler.js
package.json

Depends on #89. Fixes a lot of my broken logic for the user pill mention stuff.

Fix user pills

---

lib/BridgedRoom.js
lib/SlackGhost.js
lib/substitutions.js
tests/test-subsitutions.spec.js

The Slack API removed the ability to just send slack `@Cadair` text and have slack convert it into a mention. This is an attempt to do this substitution automatically in the bridge.
~~I would like to remove the need for the `@` here as well, which I have an idea how to do, but I am a little concerned about the performance impacts of all this.~~
This now correctly bridges plain text matrix mentions as slack mentions. This means that all matrix clients should give the correct behaviour on slack, making the bridge truly transparent. :tada: 
This also builds on #98 because of many many conflicts.

Implement bridging of plain text matrix mentions

---

lib/SlackGhost.js
lib/substitutions.js

I think this is the best solution, it fixes the pills bug for me, and also seems to not break normal links.

Remove slack link escaping because slackdown does it better

---

lib/BaseSlackHandler.js
lib/SlackGhost.js

This completely refactors `BaseSlackHandler.replaceUserIdsWithNames` to first check the UserStore for the display name and then fallback on querying slack for the display name. This means it should always be consistent with the nick of any user in the matrix room.
Signed off by: Stuart Mumford <stuart@cadair.com>

Fix the discrepancy between nicks and names in pills and mentions

---

lib/BridgedRoom.js

It seems that Slack now _does_ pass on non-JPEGs as thumbnails. I wasn't able to send any file other than `jpeg`s, previously. This quick change removes the hard-coded ".jpeg" extensions from outgoing messages in favor of their reported file-type.

Remove hardcoding JPEG as filetype in thumbnail URIs

---

lib/BridgedRoom.js
lib/Main.js
lib/SlackEventHandler.js
lib/SlackGhost.js

This adds support for the edits in riot develop bidirectionally with slack.
Slack -> Matrix edits still display the rich fallback to clients which don't speak the new edits.
builds on #129 
Signed Off By Stuart Mumford (stuart@cadair.com)

Add support for Edits

---

lib/BaseSlackHandler.js
lib/Main.js
lib/substitutions.js

This looks up rooms we bridge in the room store and then attempts to get the canonical alias for a room out of room state and replaces that in the plain text of the slack message. As much as I would like to handle proper pills replacement etc that will have to wait until we have refactored the subs.
Now with a bonus 4th commit that takes room pills from Riot and transforms them back into slack channel links.
Signed Off By: Stuart Mumford (stuart@cadair.com)

Replace channel mentions with canonical aliases for bridged rooms

---

lib/Main.js

The bot won't accept the room invite if current working dir is not writable (e.g. in k8s environment). In this case `dbdir` has to be set.
This PR ensures the bridge won't crash when `dbdir` is set, as previously only local `teams.db` path was used
Signed-off-by: Vadim Rutkovsky <vrutkovs@redhat.com>

teams.db path should use dbdir

---

package-lock.json
package.json
src/BaseSlackHandler.ts
src/BridgedRoom.ts
src/IConfig.ts
src/Main.ts
src/OAuth2.ts
src/Provisioning.ts
src/SlackEventHandler.ts
src/SlackGhost.ts
src/SlackHookHandler.ts
src/SlackResponses.ts
src/substitutions.ts

Sorry about the size of this one, but it was sort of unavoidable.
This PR changes the bridge significantly so that we now rely on `@slack/web-api` rather than doing HTTP calls ourselves, which reduces the amount of maintenance needed somewhat. API responses now also are typed and based off the slack documentation.
This PR can be treated separate from #164, but should be merged in beforehand ideally.
- pictured: reviewer wondering why these PRs are so massive

Use Slack's library for calling HTTP endpoints

---

src/Main.ts
src/SlackHookHandler.ts

This is a small fix to stop us double bridging messages when events and RTM are enabled at the same time.

Ensure we do not bridge events for teams using RTM

---

src/IConfig.ts
src/Main.ts
src/SlackHookHandler.ts
src/SlackRTMHandler.ts

This can happen when multiple channels belong to the same team and try to call the start function. This code returns early and stores a promise to ensure that future calls will await the promise.

Fix race when trying to create more than one RTM client for a team

---

changelog.d/219.bugfix
src/SlackRTMHandler.ts
src/tests/unit/SlackRTMHandlerTest.ts
src/tests/utils/fakeMain.ts

Fixes #212
This can happen when we get multiple messages for a channel while the room is being created. The provided test ensures we queue messages for a given channel.

Fix issue where DM creation can race

---

changelog.d/228.feature
package-lock.json
package.json
src/IConfig.ts
src/Main.ts

We really don't need to store all these users, as we do DB fetches for them anyway. This PR changes the default behavior so we only store 100 of each type in the cache.

Add LRU caching to matrix and slack users

---

src/Main.ts
src/SlackClientFactory.ts
src/datastore/Models.ts
src/scripts/migrateToPostgres.ts

This tweaks the migration script so it *should* migrate the old format stores into the new format with separated team tokens from rooms and all that fancy stuff.
This script has been tested to ensure it works with the 0.3.2 data format.

Migration script fixes for team refactoring

---

changelog.d/238.bugfix
src/BridgedRoom.ts

The bridge will attempt to send messages that we might not even understand. This should be filtered out before we hit Slack's API.

Do not send messages M->S if we have no content to send

---

changelog.d/246.misc
changelog.d/247.bugfix
package-lock.json
package.json
src/Main.ts
src/SlackClientFactory.ts
src/SlackEventHandler.ts
src/SlackRTMHandler.ts
src/SlackRoomStore.ts

This PR depends on #246 
This PR addresses several issues from trying to run the bridge against a set of rooms with a mixed set of data (e.g. bot tokens vs user tokens). The PR ensures that the bridge will check tokens before trying to connect using RTM, and will ensure that the bridge will run even if some rooms or teams provoke errors. The PR also ensures that RTM is connected to in parallel for each team, but is limited to a concurrency of 10 at any time.

RTM startup fixes

---

changelog.d/253.bugfix
src/BridgedRoom.ts

`is_group` is set in addition to `is_mpim` by the Slack API.

Fix multi-person DMs being registered as groups

---

changelog.d/255.bugfix
src/SlackEventHandler.ts

Fixes #248 
We currently log a stack trace on all errors, including several which don't need to be reported in such detail. Let's fix that.

Don't log stack traces for unknown teams/rooms/event

---

changelog.d/256.bugfix
src/BridgedRoom.ts
src/Main.ts
src/Provisioning.ts
src/SlackGhost.ts
src/SlackHookHandler.ts

It takes up HUGE amounts of log and leaks a lot of info

Don't log the whole response object when an error occurs

---

changelog.d/260.bugfix
src/SlackHookHandler.ts

We were previously using the values given by the oauth request, which are incomplete. I also feel somewhat uncomfortable by having multiple insertion paths for a team so let's do it this way.

Verify token and upsert team when handling an oauth response

---

changelog.d/261.bugfix
src/SlackEventHandler.ts
src/SlackHookHandler.ts
src/SlackRTMHandler.ts
src/tests/integration/SlackToMatrixTest.ts

This PR refactors our event handling so that we correctly handle Event API requests, even if using the RTM API too. This bug came up when matrix.org switched on RTM and stopped handling Events for nearly every team. While this means that RTM has more or less taken over the matrix.org deployment (yay), it also made slack turn off our Events API subscription (boo).

Always send a 200 on an Event API request

---

changelog.d/264.bugfix
config/config.sample.yaml
config/slack-config-schema.yaml
src/BaseSlackHandler.ts
src/BridgedRoom.ts
src/IConfig.ts

This fixes an issue where uploading large files will crash the bridge. The fix here is to provide a URL as a fallback if the file exceeds the configured limit.

Limit upload size

---

changelog.d/267.bugfix
src/scripts/migrateToPostgres.ts

This fixed an issue where some entries would store the bot token under a different key to `access_token`.

Fix issue where migrator cannot get the team token

---

changelog.d/269.bugfix
src/Main.ts
src/SlackGhost.ts
src/datastore/Models.ts
src/tests/integration/SharedDatastoreTests.ts

We assume here that teamId is set, where it may not be since webhooks do not have a teamId. This unbreaks bridging slack messages into Matrix by only calling toUpperCase inside the SlackGhost, if the values are given.

Fix webhooks not being able to send messages to Matrix

---

changelog.d/306.doc
docs/getting_started.md

Reverts matrix-org/matrix-appservice-slack#306
This should have been against `develop`.

Revert "tiny typos"

---

changelog.d/306.doc
docs/getting_started.md

Redoing #306 against `develop`

tiny typos - against develop

---

changelog.d/317.doc
docs/getting_started.md

Running the start application command included in the getting_started docs just shows the help window for the npm start command. This PR adds the flag that makes the command work correctly. A small typo, but important for users without much experience with npm.

Fix syntax typo for service start command

---

changelog.d/320.bugfix
src/substitutions.ts

Why a colon followed by a space, because Riot does mentions this way. Why do we care about the space? So we don't match the localparts of userIds.

Allow a trailing colon followed by a space for mentions

---

changelog.d/332.feature
src/BaseSlackHandler.ts
src/BridgedRoom.ts
src/Main.ts
src/SlackEventHandler.ts
src/SlackGhost.ts
src/TeamSyncer.ts
src/tests/utils/fakeMain.ts

This does several fancy things:
- Handles all the various ways the bridge needs to handle slack joins (it's surprisingly complex!).
- Handles leaves
- Handles invites
- Handles joining a matrix user's puppet upon joining a channel.

Membership Sync Slack <-> Matrix

---

.gitignore
changelog.d/339.bugfix
src/SlackHookHandler.ts
src/tests/unit/SlackHookHandlerTest.ts
tsconfig.json

This is to fix modular slack bridge routing issues. Tests come free.

Allow URL prefixes on webhook urls

---

changelog.d/355.bugfix
src/Provisioning.ts
src/SlackClientFactory.ts
src/tests/unit/SlackClientFactory.ts
src/tests/utils/slackTestApi.ts

We need to regularly check that the access token cached is still valid, as a validation step. This should hopefully fix things like #354. We've also cheekily cranked up the number of channels returned from a `channels` call on the provisioner.

Ensure team token is still valid

---

changelog.d/368.bugfix
src/app.ts

Fixes #360 by including the server name in the regex that determines which users the bridge controls.

Include server name in the Matrix users regex

---

changelog.d/364.doc
docs/getting_started.md

I got confused by the path of step 3 including the `config/` folder, but `config.yaml` not including the folder name.
When they both include the folder name, it's easier to tell where the new file should be placed.

Clarify path of config.yml in the docs

---

changelog.d/365.doc
docs/datastores.md

In the third line of this SQL code `slack` is used for the database name instead of `slack_bridge`.
Keeping it all the same removes the need to adapt the code sample.

Correct database name to slack_bridge

---

changelog.d/375.misc
src/AdminCommands.ts
src/Main.ts
src/Provisioning.ts
src/SlackHookHandler.ts
src/SlackRTMHandler.ts
src/tests/integration/AdminCommandTest.ts
src/tests/unit/SlackRoomStoreTest.ts

There are some obsolete `ts-lint-disabled no-any` lines in the code and some where we'll probably want to replace any with something different in the long-term.
`no-any` is currently set to warning.
I've not touched any `event: any` lines as those are basically unpredictable responses from an API.

Remove ts-lint-disable where no-any is obsolete or does matter

---

changelog.d/374.misc
src/BaseSlackHandler.ts
src/SlackEventHandler.ts
src/SlackRTMHandler.ts
src/substitutions.ts

Fixes #373
Depending on the event type `user` is:
* undefined,
* an id string or
* an ISlackUser (e.g. for the type `user_change`).

Correct ISlackEvent.user type

---

changelog.d/382.misc
package-lock.json
package.json
src/OAuth2.ts

[Deep requires have been deprecated for this package](https://www.npmjs.com/package/uuid#deep-requires-now-deprecated)

Upgrade uuid dependency

---

.gitignore
changelog.d/385.misc

Is there a command line option to place them in the ignored `logs` folder?
I find it irritating that the default path for logs isn't listed in `.gitignore`.

Add error and debug logs to .gitignore

---

changelog.d/383.misc
package-lock.json
package.json

quick-lru 5 requires NodeJS >=10.
I think this is ok, because we only test this bridge against NodeJS 10 and NodeJS 12.
If we were still supporting NodeJS 8, we should run our tests for that version.

Upgrade quick-lru dependency

---

.vscode/launch.json
changelog.d/384.misc
tsconfig.json

Adds a Launch config for VS Code, allowing to quickly start and inspect the bridge inside of VS Code.
* Not sure, if we want to have this in the repo, as it is specific to one editor.
* I locally had picked port 9999. It's unfortunate that this is hard-coded in this PR, but I didn't want to make it flexible before I know there is an interest in this PR at all.
* SourceMaps need to be enabled for breakpoints to work.

Add Launch config for VS Code

---

changelog.d/386.misc
package.json

I can't find [chalk](https://www.npmjs.com/package/chalk) directly used anywhere in our project – only dependencies seem to used it.

Remove chalk as a direct dependency

---

changelog.d/387.misc
package-lock.json
package.json

List of breaking changes:
https://github.com/vitaly-t/pg-promise/releases/tag/10.0.0
* Requires PostgreSQL 11 or later, which is the only version we're testing against anyway.
* Changes to the usage of `proc` and `func` which we are not using.

Upgrade dependency pg-promise 10

---

changelog.d/393.misc
src/datastore/postgres/PgDatastore.ts
src/tests/integration/SharedDatastoreTests.ts

Every time a user posts in a room they have already posted in on that day, the bridge outputs an error, if the metrics are enabled:
```
Apr-16 11:24:55.729 ERROR BridgedRoom Error storing activity metrics error: duplicate key value violates unique constraint "cons_activities_unique"
at Connection.parseE (/home/jaller94/Git/Matrix/matrix-appservice-slack/node_modules/pg/lib/connection.js:614:13)
at Connection.parseMessage (/home/jaller94/Git/Matrix/matrix-appservice-slack/node_modules/pg/lib/connection.js:413:19)
at Socket.<anonymous> (/home/jaller94/Git/Matrix/matrix-appservice-slack/node_modules/pg/lib/connection.js:129:22)
at Socket.emit (events.js:315:20)
at addChunk (_stream_readable.js:297:12)
at readableAddChunk (_stream_readable.js:273:9)
at Socket.Readable.push …
```

Fix PostgreSQL errors when a metric activity is recorded twice

---

changelog.d/401.feature
src/Main.ts

(CC: @jryans)
If a channel is bridged to a room, ensure that it won't be bridged somewhere else without first being removed from the old room.

Disallow bridging to channels that are already bridged

---

changelog.d/397.feature
config/config.sample.yaml
config/slack-config-schema.yaml
src/IConfig.ts
src/Main.ts
src/Provisioning.ts
src/SlackClientFactory.ts
src/SlackHookHandler.ts
src/datastore/Models.ts
src/datastore/NedbDatastore.ts
src/datastore/postgres/PgDatastore.ts
src/tests/utils/fakeDatastore.ts

~~This is still missing functionality to handle the removal of team clients~~ Punting to https://github.com/matrix-org/matrix-appservice-slack/issues/399
This PR does 4 things:
- It limits the number of bridged rooms that can be created by config.
- It limits the number of teams that can be connected.
- It exposes a flag for whether the configured instance allows private rooms to be bridged to channels.
- It exposes these limits in a config endpoint.

Add configuration to limit teams and rooms counts

---

.dockerignore
Dockerfile
changelog.d/405.bugfix
package-lock.json
package.json

I have a suspicion that pg-promise broke on Node v14, as we're seeing people complaining about being unable to use postgres on the latest image, which is using Node v14.
To fix, I've updated pg-promise to a version compatible with Node v14, and also pinned us to Node v14 in order to ensure we don't get caught out next time. At some point, we should include Node v14 on our pipeline.

Pin Dockerfile node version

---

changelog.d/403.bugfix
config/config.sample.yaml
config/slack-config-schema.yaml
src/IConfig.ts
src/Provisioning.ts
src/datastore/postgres/PgDatastore.ts

This requires us to determine the identity of the caller in order to check if they are *in* the channel. Luckily, there is an endpoint for that :)

Allow bridging of private channels via the provisioner

---

changelog.d/409.bugfix
src/Provisioning.ts

We are accidentally calling the wrong endpoint. Bah.

Fix stupid endpoint call bug

---

changelog.d/410.misc
package-lock.json
package.json

In order to pull in `pg` 8.1, which allows us to use parameters like `?ssl=no-verify`

Update to pg-promise 10.5.5

---

changelog.d/416.misc
config/config.sample.yaml

I think `users` should be on the same nesting level as `channels`.

Fix team_sync indentation in sample config

---

changelog.d/415.misc
src/app.ts

Same as matrix-org/matrix-appservice-gitter#99. This is probably the first time I had typescript file open in editor, let me know if something needs to be changed :grinning:
----
When the app was started from directory other than the top-level of the repository, following error happens:
```
fs.js:114
throw err;
^
Error: ENOENT: no such file or directory, open 'config/slack-config-schema.yaml'
at Object.openSync (fs.js:443:3)
at Object.readFileSync (fs.js:343:35)
at ConfigValidator._loadFromFile (/nix/store/kv4w6rqv49jimq961wq3l7mx10cwzbr9-node_matrix-appservice-slack-1.3.1/lib/node_modules/matrix-appservice-slack/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:63:29)
at new ConfigValidator (/nix/store/kv4w6rqv49jimq961wq3l7mx10cwzbr9-node_matrix-appservice-slack-1. …
```

Load schema using absolute path

---

changelog.d/419.feature
src/Main.ts
src/Provisioning.ts
src/SlackClientFactory.ts
src/SlackHookHandler.ts
src/datastore/Models.ts
src/datastore/NedbDatastore.ts
src/datastore/postgres/PgDatastore.ts
src/datastore/postgres/schema/v6.ts
src/tests/utils/fakeDatastore.ts

This PR does a lot, but unfortunately it's mostly intertwined and had to be done in a block. I'll try to explain the situation as it is now:
Currently, users run through the oauth flow and we store the resulting access token / slack id and team id into the "accounts" json object inside a `MatrixUser`, which is stored as a JSON blob in the database. A holdover from the NeDB days. This made it difficult to run queries to tell which users were connected to which slack team.
This became a problem for account logout / removing teams. There isn't a good way to tell if a team is unused, or the user is the last account holder for that team because iterating over all those JSON blobs is difficult. We deferred handling this, and simply deleted the account from the user object so they couldn't see …

Refactor account handling to solve account logout issues

---

changelog.d/422.misc
src/AdminCommands.ts
src/OAuth2.ts
src/Provisioning.ts
src/SlackHookHandler.ts

This is actually implemented in #421 but I've split it into this PR to make reviewing that PR easier. We used to support authenticating via oauth to allow for richer bridging with webhooks, but to be honest it's a bit pointless when you can do the whole thing through oauth without having to setup cumbersome webhooks.
We actually stopped this from working ages ago, so this is just a cleanup mission.

Drop support for oauth with webhooks

---

changelog.d/420.bugfix
src/datastore/postgres/PgDatastore.ts
src/datastore/postgres/schema/v7.ts

We accidentally made it so that two puppets could never be registered against the same mxid, or the same team_id. Let's fix that. Using `v7` because `v6` is part of #419

Fix puppets being constrained by team / matrix id

---

changelog.d/429.misc
src/datastore/Models.ts
src/datastore/NedbDatastore.ts
src/datastore/postgres/PgDatastore.ts
src/tests/utils/fakeDatastore.ts

This is #429 with modifications to make our TypeScript types happy.
Added by me:
* Fixed: .map() was not returning an object.
* Changed: All database methods that returned `void` now return `null` for consistency and because that's what our main storage lig `pg-promise` does.
New PR because for some reason Git did not want to push to the old branch. :/
If you figure out how, you can also cherry-pick 0fca58486e7ce474937766678f3ae92c11488a93 onto the other branch.

Update PgDatastore.ts (with modifications)

---

.vscode/launch.json
changelog.d/436.doc
config/config.sample.yaml

Our Docker image uses port TCP 5858, so we may as well suggest it as the appservice port consistently.

Consistently suggest to use port 5858 for the appservice

---

changelog.d/440.bugfix
src/Main.ts
src/app.ts

Fixes #441
The CLI class expects its port to be used but the bridge may override that with an optional value from the config.
Only affects console output. The behaviour was not actually broken.

Print the correct appservice port on the console when using the one from the config

---

changelog.d/443.misc
src/AdminCommand.ts

It's not used anywhere, so I would like to not allow `string[]` to reduce complexity and potential logic errors when calling `.includes` on it further down in the file.

Don't allow string[] commands

---

changelog.d/445.bugfix
src/AdminCommand.ts
src/AdminCommands.ts

Includes #443 
`help foo` searched for a method `foo` on AdminCommands. `help oauth` was broken, because the method has a different name.
But other class methods could be called, even though they are not admin commands.
Other examples like this: `help yargs`, `help commands`, `help constructor`, `help __prototype__`. 😐️
I haven't found any security issues or ways to crash the bridge with to this, however, I think this PR mitigates the risk that there is a way to exploit this.

Fixes the admin command "help oauth" and better types for AdminCommands

---

changelog.d/454.bugfix
src/TeamSyncer.ts

The random delay before calling Slack's API for more channels or users is calculated incorrectly.
1. `Math.random() * anything` can be 0. Given a minimum is specified, this will give us an uneven distribution, leaning to the minimum.
2. `Math.min()` gave us the smaller number, which means the result was always between 0 and MIN, not between MIN and MAX.
My new implementation assumes that MIN is below MAX and that both are positive. I think having no validation is reasonable, as the numbers are specified in code and not configurable.

Stop Team Sync from calling Slack's API more rapidly than configured

---

changelog.d/456.bugfix
src/Main.ts
src/TeamSyncer.ts

Failing user or channel syncs are currently resulting in an uncaught promise. That a deprecated functionality of Node, which will crash the end the process soon anyway and would lead to inconsistent behaviour.
Also, .setAvatarUrl requires a string. The Element client resets the avatar by providing an empty array, so this fixes #453.
```javascript
const teams = [,,];
const promiseFunctions = [];
let i = 0;
for (const team of teams) {
i++;
promiseFunctions.push(async() => {
console.log(`${i} of ${teams.length}`);
});
}
promiseFunctions.forEach(func => func());
```
outputs
```
3 of 3
3 of 3
3 of 3
```
because at the time the promises execute, the variable `i` from the outer context already has its final value 3.

Correctly bubble up rejected promises from TeamSync

---

changelog.d/455.bugfix
src/datastore/NedbDatastore.ts

Fixes #352 by returning after resolving.

Fix NedbDatastore.getTeam when an error happened or the team doesn't exist

---

changelog.d/475.feature
src/Main.ts

We currently sync users and channels on startup, but this less useful if you've just added your team.

Sync users and channels on new team setup

---

changelog.d/477.bugfix
src/SlackEventHandler.ts

This ensures we still create and remove rooms for channels in realtime rather than during startup.

Subscribe to additional events on the RTM API

---

changelog.d/476.feature
config/config.sample.yaml
config/slack-config-schema.yaml
src/AllowDenyList.ts
src/IConfig.ts
src/Main.ts
src/TeamSyncer.ts
src/tests/unit/AllowDenyListTest.ts

This allows us to A/D channels from being bridged across on startup or through the provisioner based on name or id.

Add configuration to deny slack channels by name or ID

---

changelog.d/478.bugfix
src/BridgedRoom.ts
src/TeamSyncer.ts

When the slack side bot joins the room, it gets reflected to Matrix. Since we never expect the bot to "speak" in the conversation, it's presence in the room is unwanted.

Do not reflect the bridge bot to Matrix

---

changelog.d/482.bugfix
src/AllowDenyList.ts
src/BridgedRoom.ts
src/Main.ts
src/SlackEventHandler.ts
src/SlackHookHandler.ts

Notably:
- Improve chances of catching duplicate messages when puppeting
- Fix issue where syncing a team for the first time will fail to sync channels or users
- Ensure ghosts will leave a PM room if they were blocked by a ADL.
Fixes #481

Small tweaks for puppeting code

---

changelog.d/520.feature
src/AdminCommand.ts
src/tests/unit/AdminCommandTest.ts

`link room [channel_id] [slack_bot_token] [team_id] [webhook_url]`
becomes
`link --room ROOM [--channel_id CHANNEL_ID] [--slack_bot_token SLACK_BOT_TOKEN] [--team_id TEAM_ID] [--wbehook_url WEBHOOK_URL]`.
Without that it is impossible to tell which parameters are positional or not. I always fails once when trying to type a command.

Show flags in the help

---

changelog.d/525.feature
src/BaseSlackHandler.ts

Do not fail to bridge slack message if an alias doesn't exist

---

changelog.d/528.bugfix
src/BridgedRoom.ts

If a puppeted user starts typing on Matrix, the bridge will currently reflect that as their remote user typing. We should hide the typing notifications for users we puppet.

Hide typing from puppeted users

---

Dockerfile
changelog.d/531.feature

We copy only npm related files first, so we can use the cache and not run again
`npm install` when only the code changes.
Signed-off-by: Alexandre Morignot <erdnaxeli@cervoi.se>
This speeds up a bit development time, when using the docker image to test (as I do).

Minimize docker build time

---

changelog.d/545.doc
docs/getting_started.md

I personally ran into an issue where I upgraded matrix-appservice-slack and didn't realize I should only rebuild and restart the appservice, not also generate a new appservice registration file, etc. This adds an Upgrading section to the documentation and identifies which steps to take specifically, with a note to NOT regenerate the registration file.

documentation: clarify upgrade instructions

---

changelog.d/553.bugfix
src/datastore/postgres/PgDatastore.ts
src/datastore/postgres/schema/v11.ts

Fixes #552
Fixes months to be zero-based and migrates old data.
This bug only affects our PostgreSQL adapter. Metrics are not supported by our NeDB adapter.

Fix metrics bug: Month has been off by one (e.g. January = 0)

---

changelog.d/544.bugfix
src/Main.ts
src/TeamSyncer.ts
src/app.ts

This was using the wrong option as pointed out by @MadLittleMods (https://gitlab.com/gitterHQ/webapp/-/merge_requests/2053).
We need to be careful here, because I can imagine making this work would introduce a breaking change insofar that if the aliases start working, the HS may reject the request because the registration file hasn't included the correct namespace.
The configuration to set aliases is behind a configuration flag, and I've ensured that generated registration files will include the correct alias prefixes.

Fix public rooms being created without aliases

---

changelog.d/577.feature
config/config.sample.yaml
config/slack-config-schema.yaml
src/TeamSyncer.ts

This is to allow people to sync their private channels without having to worry about their public ones also being bridged (for instance if they run a seperate sync tool for public channels aka @Cadair )

Allow public channel syncing to be disabled independently of private

---

src/Main.ts
src/Provisioning.ts

I don't think we consider this to be confidential for Matrix users who have a puppet on the Slack server.

ProvisioningAPI.channelinfo: Differentiate between not found and not allowed

---

changelog.d/587.misc
config/config.sample-complete.yaml
config/config.sample.yaml
config/slack-config-schema.yaml

Replaces #566 by fixing both config samples

Config samples: Corrected rtm.logging to rtm.log_level; Schema: rtm.log_level: "off" -> "silent"

---

changelog.d/566.doc
config/config.sample.yaml

according to the code and the spec it's supposed to be log_level instead of logging.
really annoying when you try to debug why RTM doesn't work and the setting is buggy itself :P

fix wrong config key name

---

changelog.d/599.bugfix
src/Main.ts
src/TeamSyncer.ts

To avoid one throwing and taking out the other one. This PR also refactors the team syncer to split out users and channels to separate functions to make the code easier to follow and debug.

Sync channels and users of a team independently

---

changelog.d/601.feature
config/config.sample-complete.yaml
config/config.sample.yaml
src/TeamSyncer.ts

Since the hint how to invite the bridge could be not wanted there should
be a option to disable this. This commit introduce a simple boalean flag
which makes the message configuarable for users.
Signed-off-by: Jan Luca Naumann <j.naumann@fu-berlin.de>

Make the team sync hint to channel admins configurable

---

Dockerfile
changelog.d/614.misc
config/config.sample-complete.yaml
config/config.sample.yaml
config/slack-config-schema.yaml
package-lock.json
package.json
src/AdminCommand.ts
src/BaseSlackHandler.ts
src/BridgedRoom.ts
src/IConfig.ts
src/Main.ts
src/Provisioning.ts
src/SlackClientFactory.ts
src/SlackEventHandler.ts
src/SlackGhost.ts
src/TeamSyncer.ts
src/app.ts
src/datastore/Models.ts
src/datastore/postgres/PgDatastore.ts
src/substitutions.ts
tests/unit/ConfigTest.ts
tests/unit/SlackClientFactory.ts
tests/utils/fakeIntent.ts
tests/utils/harness.ts
tsconfig.json

This PR ended up being quite large, but this migrates us to `matrix-appservice-bridge` 3.0.0 with a few linting tweaks and improvements along the way.
This PR currently depends on ~~two~~ one unmerged PRs:
- ~~https://github.com/matrix-org/matrix-appservice-bridge/pull/357~~ No longer required. Going to do this in a separate PR.
- https://github.com/matrix-org/matrix-appservice-bridge/pull/355
We also had to stop checking our dependency types due to https://github.com/turt2live/matrix-bot-sdk/issues/155

Upgrade to matrix-appservice-bridge 3.0.0

---

changelog.d/612.feature
config/config.sample-complete.yaml
config/config.sample.yaml
src/IConfig.ts
src/Main.ts
src/datastore/Models.ts
src/datastore/NedbDatastore.ts
src/datastore/postgres/PgDatastore.ts
src/datastore/postgres/schema/v13.ts
tests/utils/fakeDatastore.ts

Sister PR with https://github.com/matrix-org/matrix-appservice-irc/pull/1472, based on https://github.com/matrix-org/matrix-appservice-bridge/pull/350.
Drafting since I'm planning to move some code duplicated between -slack and -irc into bridge to reduce duplication.

Implement RMAU limits and bridge blocking

---

changelog.d/628.bugfix
src/BridgedRoom.ts
src/Main.ts
src/MatrixUser.ts
tests/unit/MatrixUserTest.ts

Inspired by https://github.com/Half-Shot/matrix-appservice-discord/blob/develop/src/matrixeventprocessor.ts#L425, which we should probably integrate in MAB to not duplicate this logic everywhere.

Fallback to profile lookup if we don't have membership data for a user+room pair

---

Dockerfile
changelog.d/645.misc

Fixes #643 
This was due to alpine having funky DNS issues which led to lots of ENOTFOUND errors, we never truly got to the bottom of it but found that debian fixed the issue. The bridge doesn't rely on any particular operating system quirks so it's fine to just use the base debian image.

Use debian for docker images

---

changelog.d/648.bugfix
src/BridgedRoom.ts

Hey there @Half-Shot , this logic error was activated when the promise stuff was tidied up, and stops the bridge sending messages to the matrix room.

Fix inverted check if message was sent

---

changelog.d/664.misc
package-lock.json
package.json

Instead of upgrading follow-redirects in #662, I propose to upgrade axios which upgraded the vulnerable sub-dependency in https://github.com/axios/axios/pull/4473.

Upgrade dependency axios to 0.26.0

---

.eslintrc.js
changelog.d/665.misc
src/BridgedRoom.ts
src/Main.ts
src/OAuth2.ts
src/SlackGhost.ts
src/SlackRTMHandler.ts
src/rooms/UserAdminRoom.ts
src/scripts/migrateToPostgres.ts

`substr()` has been deprecated. For all the remaining uses in this code base `slice()` bahaves the same.

Remove uses of the deprecated JavaScript function substr()

---

changelog.d/669.bugfix
src/Main.ts

Because the parameters were swapped a new ping room is created on every bridge restart.
We don't include a cleanup of false entries as they are no harm and there hasn't been a stable release since this was introduced in PR #666.
Issue description: https://github.com/matrix-org/matrix-appservice-slack/pull/666/files#r818765045

Fix: Don't create an internal ping room on every restart

---

changelog.d/673.feature
src/BridgedRoom.ts
src/SlackGhost.ts

Fixes #673.
I don't know if any backwards compatibility is needed for the unstable ones added in #668, but I don't think that's seen a release yet, so I hope not?

Use the stable threads relations from MSC3440.

---

changelog.d/670.misc
src/datastore/postgres/PgDatastore.ts
src/datastore/postgres/schema/v14.ts

The models expect all these values to be defined (not null). Allowing `NULL` for these columns in PostgreSQL is against the expected types of the `EventEntry`.
https://github.com/matrix-org/matrix-appservice-slack/blob/848c68c57fbfab62a2b05ccb4a0e99bbb3e3ff63/src/datastore/Models.ts#L44-L50
```
Column    | Type | Collation | Nullable | Default 
--------------+------+-----------+----------+---------
roomid       | text |           |          | 
eventid      | text |           |          | 
slackchannel | text |           |          | 
slackts      | text |           |          | 
extras       | text |           |          | 
Indexes:
"cons_events_unique" UNIQUE CONSTRAINT, btree (eventid, roomid, slackchannel, slackts)
"events_matrix_idx" btree (roomid, eventid)
"events_slack_idx" btree …
```

Don't allow NULL in PostgreSQL columns of events

---

changelog.d/677.misc
scripts/towncrier.sh

```
./scripts/towncrier.sh 
towncrier, version 21.9.0
```
```
./scripts/towncrier.sh
Loading template...
Finding news fragments...
Rendering news fragments...
Writing to newsfile...
Staging newsfile...
Removing news fragments...
I want to remove the following files:
/home/jaller94/Git/matrix-appservice-slack/changelog.d/664.misc
…
```

Make towncrier build the news instead of printing its version

---

changelog.d/649.bugfix
src/TeamSyncer.ts

Which should avoid the # of HTTP hits needed.

Only leave deleted users from rooms they are part of in Team Sync

---

changelog.d/709.bugfix
src/SlackGhost.ts

This adds the flag to the thread which tells clients the reply is included as a fallback, this should stop slack threads displaying as replies in threads.
fixes #708

Add falling back to threads

---

changelog.d/722.bugfix
src/BridgedRoom.ts
src/SlackRTMHandler.ts

Inviting a Slack ghost to a DM won't invite the ghost for your own Slack user, meaning that messages you send in that DM from Slack can only be bridged if your Slack ghost is in the Matrix DM.  This PR ensures that your Slack ghost gets invited when you send a message in Slack.

Invite own ghost in DMs if needed

---

changelog.d/720.misc
docs/getting_started.md

Most typically, one would run bridge container as daemon to prevent it from stopping.

Docs: Run bridge as daemon

---

changelog.d/725.bugfix
src/AdminCommand.ts
src/AdminCommands.ts
src/Main.ts

Fixes #724
The crash caused by this kind of admin command errors is a regression in 2.0.2-rc1, but in 2.0.1, they would be ignored & the bridge bot would just say "Done".

Handle admin command errors
